version: '3'
services:
  posterr-api:
    build: .
    image: thiagocf/posterr-api:prod
    container_name: posterr-api
    entrypoint: dockerize -wait tcp://db:5432 -timeout 30s docker-entrypoint.sh
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - posterr-net
    restart: always
    env_file:
      - env/docker-db.env
    command: ./scripts/start.sh

  db:
    image: postgres
    container_name: posterr-db
    networks:
      - posterr-net
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - env/docker-db.env

networks:
  posterr-net:
    driver: bridge